id: PC606A64A
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni Prayers & Practices
  language: de
  description: 'Lotsawa House presents the following texts as part of its Prayers
    to Buddha Śākyamuni Series:'
  volume:
    4aabdf13a2de4f7d8c7ddc1e0f7b0873:
      title: Prayer for the Future of the Dharma
      parent: Aspiration Prayers
    d14b011815724465b06bc030843d416c:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Aspiration Prayers
    21b007a1e4c64bec86922a8d01a5cd74:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Aspiration Prayers
    30dae371fa2f41939483c61aa9068915:
      title: Verses on the Buddha's Previous Lives
      parent: History
    94d755eb5eb1493ba83e6c2fa97cdffb:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha's Deeds
    7c266cd4c3b944d6863b505fcc459a26:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha's Deeds
    6eb8c4fb4fa84f00bbd432abf5b3027f:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha's Deeds
    eb5026e6a9b042b882f0cc5f2a3641b9:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    80888f04b8d54a9184ceb6c261cb3164:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    f238016886e84d84be8631764e92e9ee:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    5bd7d488bfec43b4a15fd1734c585165:
      title: A Practice of Paying Homage and Making Offerings to the Sixteen Elders
      parent: Sādhanas
    ec8cddfccefc4207806ed577963636c9:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Sādhanas
    115dd3cc09724c82bee3ca422212ef80:
      title: 'The Sage who Dispels Mind’s Anguish: Advice from the Guru, the Gentle
        Protector Mañjuśrī on the Means of Accomplishing the Yogas of Śamatha and
        Vipaśyanā'
      parent: Commentaries
created_at: '2022-03-01T03:05:43.224054'
last_modified_at: '2022-03-01T03:05:43.224057'
